### ISSUE TITLE
Unused variable p in main.cc

### ISSUE THREAD

**Issue by lawless-m** [petershirley/raytracinginoneweekend#1]
p is never used in main.cc

89: vec3 p = r.point_at_parameter(2.0);
90: col += color(r, world,0);

should the r in 90: be p ?

**Comment by lawless-m** [comment]
ugh, I should have tried it, wrong type. But still, p doesn't seem to do anything.

Point_at_parameter has no side effects

**Comment by justuswilhelm** [comment]
I ended up just removing the line when working through the book. It does not appear to serve a purpose.

**Comment by petershirley** [comment]
Good eye.   That looks like dead code.

Pete

**Comment by LYP951018** [comment]
It seems that p is the point that the ray intersecting with the film plane? (not the focal plane)
