### ISSUE TITLE
math error in sphere.h?

### ISSUE THREAD

**Issue by CrzDog** [petershirley/raytracinginoneweekend#13]
on line 33 in sphere.h
a little misleading perhaps...
if (discriminant > 0)  -> if (discriminant >= 0)    may be better?

**Comment by petershirley** [comment]
Maybe!   I think 0 is the grazing case and that is where the cosine with
the normal will be 0 or even a little negative.   So I usually go with >.
But this is not a strongly held optinion

Pete
