### ISSUE TITLE
main.cc - used variable p

### ISSUE THREAD

**Issue by alexnardini** [petershirley/raytracinginoneweekend#14]
At line number 100 of "main.cc" :
`vec3 p = r.point_at_parameter(2.0);`
I think this is not needed at all, is it?

**Comment by vchizhov** [comment]
It is not, it's just something leftover from a prev version most likely.

**Comment by alexnardini** [comment]
Thank you for confirming.

**Comment by hollasch** [comment]
Duplicate of #1
