### ISSUE TITLE
incorrect discriminant formula

### ISSUE THREAD

**Issue by nicolas-modsy** [petershirley/raytracinginoneweekend#17]
https://github.com/petershirley/raytracinginoneweekend/blob/0abfd4c3e0d6fcb932d087832706ac968675a72e/sphere.h#L32

`    float discriminant = b*b - a*c;`

should be

`    float discriminant = b*b - 4*a*c;`

**Comment by nicolas-modsy** [comment]
from the book:

> Note that I eliminated a bunch of redundant 2's that cancel each other.

**Comment by madeinsoviets** [comment]
The current equation produces incorrect results:

Discriminant formula is D = b^2 - 4ac
and the roots of the equation should be (-b +/- sqrtf(D)) / 2*a
the 2 multiplier is not redundant and not cancels itself

**Comment by amesgames** [comment]
I have been trying to resolve this issue, as well. If I correct the formula in the code, many of the spheres no longer draw and the large one used as a ground plane appears very eyed.

**Comment by amesgames** [comment]
Peter Shirley has the correct equation. The canceling "2" comes from the calculation of the scalar **b**. See https://www.scratchapixel.com/lessons/3d-basic-rendering/minimal-ray-tracer-rendering-simple-shapes/ray-sphere-intersection.

In chapter 4, "Adding a sphere", Peter shows that b = 2 * dot(OC, ray.direction). If you follow that 2, it gets squared to become 4, then can be factored out of both terms of the discriminant. sqrt makes the 4 2 and it cancels the 2 in the denominator.

**Comment by ronnieholm** [comment]
Have a look at

http://bugfree.dk/blog/2018/09/03/ray-tracing-computing-ray-sphere-intersections

Towards the end, the modified root formula from the book is derived step by step.
