### ISSUE TITLE
FYI Only - Kotlin Conversion

### ISSUE THREAD

**Issue by time4tea** [petershirley/raytracinginoneweekend#21]
Hi,

I was stuck in for a day and saw your nice mini-book. I thought it might be fun to see this working in kotlin, so I wrote it in kotlin.... 

I tried to keep variables etc the same as you mostly, so it should be very easy to compare.

There are a couple of changes - it uses coroutines (badly) (so uses all cores) and renders the image unto a UI window as its computing it (also badly!), so its a bit more interactive.

There may be some bugs in my conversion...

The code is at: https://github.com/time4tea/raytrace-in-a-weekend-kotlin

Hope that's useful.

Cheers

James

**Comment by petershirley** [comment]
Cooll!  I don’t know of kolton.   It looks like java but has (to me
essential for ray tracing) operator overloading?   I looked at it and it
seems like it’s java++.  Pretty!

Can i tweet that?

**Comment by time4tea** [comment]
Hi Peter. Of course you can tweet it :-) if you want to mention me in the tweet, my twitter handle is @richajam 

The language - kotlin - is relatively new. It runs on the JVM and has a nice syntax and a decent type system. It also compiles (experimentally) to native code or javascript so can be used in browser.

The project will open directly in IntelliJ Community Edition if you want to see it in action.

Glad you like it. Thanks again for the minibook!

James

**Comment by hollasch** [comment]
Added link from wiki.
