### ISSUE TITLE
Chapter 5: constants missing from terms in sphere::hit

### ISSUE THREAD

**Issue by ronnieholm** [petershirley/raytracinginoneweekend#52]
Within sphere::hit on Page 16

    float discriminant = b*b - a*c;

should be

    float discriminant = b*b - 4*a*c;

Similarly when expression is repeated in the two square root expressions a few lines below. Those should probably be sqrt(discriminant).

**Comment by hollasch** [comment]
The code is correct. See commentary in duplicate issue #17.

**Comment by ronnieholm** [comment]
Odd. With my implementation the resulting image isn't correct unless I adjust the discriminant formula. Probably some error on my part then.

**Comment by hollasch** [comment]
There's some unguided trickery there. If you look at the example code in chapter 4, you'll see the lines as you expect. However, note the multiplication by `2.0` for variable `b`. If you take the quadratic formula and replace `b` with `2d`, then you'll get

    roots = (-2d ± sqrt((2d)^2 - 4ac)) / 2a

This will then simplify as follows:

    roots = (-2d ± sqrt(4d^2 - 4ac)) / 2a
    roots = (-2d ± 2*sqrt(d*d - a*c) / 2a
    roots = (-d ± sqrt(d*d - a*c) / a

Here, `d = dot(oc, r.direction())` (the original b was `b = 2.0 * dot(oc, r.direction())`.
