### ISSUE TITLE
Extraneous semi-colon in vec3.h

### ISSUE THREAD

**Issue by michaelhiatt** [petershirley/raytracinginoneweekend#6]
Enjoying the book so far, though I am only very early on so far.

I believe there may be an unneeded semicolon in the following line:

`inline float& operator[](int i) { return e[i]; };`

**Comment by petershirley** [comment]
Good call!

Have you seen this-- you'll see why it reminded me!

https://twitter.com/pelotom/status/779134762283732992?lang=en

Pete
